// <auto-generated />
using System;
using GatePassManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GatePassManagementSystem.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260705130015_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GatePassManagementSystem.Models.EntityModels.TblAdminAccessDetails", b =>
                {
                    b.Property<int>("TblId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TblId"));

                    b.Property<DateTime>("LogINdate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LogINtime")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("TblId");

                    b.ToTable("TblAdminAccessDetails");
                });

            modelBuilder.Entity("GatePassManagementSystem.Models.EntityModels.TblAdminUserDetails", b =>
                {
                    b.Property<int>("TblId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TblId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Username")
                        .HasColumnType("int");

                    b.HasKey("TblId");

                    b.ToTable("TblAdminUserDetails");
                });

            modelBuilder.Entity("GatePassManagementSystem.Models.EntityModels.TblAllApprovedRequests", b =>
                {
                    b.Property<int>("TblId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TblId"));

                    b.Property<string>("ApprovedPerson")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("DPM")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EPF")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("InTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RequestApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserRoleType")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("TblId");

                    b.ToTable("TblAllApprovedRequests");
                });

            modelBuilder.Entity("GatePassManagementSystem.Models.EntityModels.TblAllFinalDetailsOfApprovedRequests", b =>
                {
                    b.Property<int>("TblId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TblId"));

                    b.Property<DateTime>("ActualInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ActualOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedPerson")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("CheckBy")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("DPM")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EPF")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("InTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RequestApprovedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RequestCreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("UserRoleType")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("TblId");

                    b.ToTable("TblAllFinalDetailsOfApprovedRequests");
                });

            modelBuilder.Entity("GatePassManagementSystem.Models.EntityModels.TblAllPendingRequests", b =>
                {
                    b.Property<int>("TblId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TblId"));

                    b.Property<string>("DPM")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EPF")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("EmployeeRole")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("InTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RequestCreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("UserRoleType")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("TblId");

                    b.ToTable("TblAllPendingRequests");
                });

            modelBuilder.Entity("GatePassManagementSystem.Models.EntityModels.TblAllRejectedRequests", b =>
                {
                    b.Property<int>("TblId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TblId"));

                    b.Property<string>("DPM")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EPF")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("EmployeeRole")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("InTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RejectedPerson")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("RequestCreatedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RequestRejectedDate")
                        .HasColumnType("date");

                    b.Property<string>("UserRoleType")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("TblId");

                    b.ToTable("TblAllRejectedRequests");
                });

            modelBuilder.Entity("GatePassManagementSystem.Models.EntityModels.TblUserAccountDetails", b =>
                {
                    b.Property<int>("TblId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TblId"));

                    b.Property<string>("DPM")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<byte[]>("EmployeePhoto")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ReportingManager")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ReportingSupervisor")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserRoleType")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Username")
                        .HasColumnType("int");

                    b.HasKey("TblId");

                    b.ToTable("TblUserAccountDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
